### ISSUE TITLE
Google Map doesn't work

### ISSUE THREAD

**Issue by RamyAlshurafa** [katpas/inshallahapp#192]
Google map doesn't work, needs to update the API key

**Comment by thejoefriel** [comment]
@RamyAlshurafa as discussed please send @Sarafallan step-by-step details on how to add her card details to get the monthly free $200 that google provides.

**Comment by RamyAlshurafa** [comment]
Hey @Sarafallan 
here is step by step how to get API key from Google Maps
 - visit https://cloud.google.com/maps-platform/?apis=maps
- sign in (from the right and up corner)
- click on `Get Started`
![1](https://user-images.githubusercontent.com/34629478/55032952-0fc29a80-5023-11e9-94e5-4f7f956ffc42.png)

-  select `Maps` then `continue`
![2](https://user-images.githubusercontent.com/34629478/55033047-4b5d6480-5023-11e9-9d61-3bb11ab8ff27.png)
- select `inshallah` then `next`

![3](https://user-images.githubusercontent.com/34629478/55033219-ae4efb80-5023-11e9-9b06-5c9604222ec2.png)

- then `Create Billing Account`

- then go on filling the form settings
   * choose the country 
   * add your info

- then you can get the key
![4](https://user-images.githubusercontent.com/34629478/55034010-82cd1080-5025-11e9-969c-6368feaf1781.png)

and here is a short youtube video that shows the same steps above
https://www.youtube.com/watch?v=DwS0U1JmXVU

If you faced any problem please let me know

**Comment by Sarafallan** [comment]
Hi guys,
Thanks for this. This is done! I've now signed up to the "free trial"
Best,
Sara

**Comment by RamyAlshurafa** [comment]
Done!
